name: Use Secret Workflow

on:
  push:
    branches:
      - main # Or your default branch, e.g., master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use the secret
      run: |
        echo "Attempting to use the secret securely..."
        # Example: Using the secret with a dummy command
        # This is a placeholder. In a real scenario, you'd use the secret
        # to authenticate to an API or perform a secure operation.
        # The key is to ensure the secret itself is NOT printed to logs.
        # For example, sending it as an environment variable to a script:
        echo "::add-mask::${{ secrets.SECRET }}" # Masks the secret in logs
        # DUMMY_SECRET_VAR="${{ secrets.SECRET }}"
        # echo "Secret processed."
        # For demonstration purposes, we'll just acknowledge its presence securely.
        echo "Secret accessed successfully (value masked in logs)."
        # DO NOT echo the actual secret value directly: echo "${{ secrets.SECRET }}"

    - name: Verify a non-sensitive output (optional)
      run: |
        echo "Workflow completed successfully."
