name: Use Secret Demo

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use secret in masked way
      run: |
        echo "Using the secret securely..."
        echo "The secret is \${{ secrets.SECRET }}" > secret_output.txt
        echo "::add-mask::${{ secrets.SECRET }}"
        echo "Secret written to file, but masked in logs."
